# SITE CONFIGURATION
title: David Van Dyke # your site title
author: David Van Dyke # You :P
description: > # Meta description of Homepage
  Portfolio website for David Van Dyke
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dhvd.net/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: David Van Dyke
  links:
    - https://www.instagram.com/dhvd_/?hl=en
    - https://www.facebook.com/david.h.vandyke.9/
    - https://www.linkedin.com/in/dhvd03

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Portfolio', link: '/portfolio'}
  - {name: 'Resume', link: '/resume'}

tagline: >
  dhvd@stanford.edu

hero_img: posts/background.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: dhvd@stanford.edu # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
instagram_username: dhvd_ # replace with your_instagram_username or comment to remove link from footer
linkedin_username: dhvd03
facebook_username: david.h.vandyke.9

# disqus:
#   shortname: dhvd # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-NDMSGSW # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  stype: compressed
